const fs=require('fs');const path=require('path');const ts=require('typescript');const vm=require('vm');const assert=require('node:assert/strict');
const cache={};function load(file){file=path.resolve(file);if(cache[file])return cache[file];const sandbox={exports:{},require:id=>load(path.resolve(path.dirname(file),id+'.ts'))};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,sandbox);cache[file]=sandbox.exports;return sandbox.exports;}
const catalog=load('src/onboarding/model.ts');const m=load('src/socialModel.ts');let count=0;function check(name,fn){fn();count++;console.log('PASS',name);}
check('Catalog IDs are unique and every section reference resolves',()=>{assert.equal(new Set(catalog.INTERESTS.map(i=>i.id)).size,catalog.INTERESTS.length);assert(catalog.INTEREST_GROUPS.every(g=>g.ids.every(id=>catalog.INTERESTS.some(i=>i.id===id))));});
check('Same year and shared interests rank first',()=>{assert(m.suggestions(['strength'],'First year').slice(0,2).every(p=>p.year==='First year'&&p.shared.includes('strength')));});
check('A named yoga class discovers broader yoga friends and one group family',()=>{assert(m.suggestions(['flow-yoga'],'Junior').some(p=>p.id==='noor'));assert.equal(m.groupSuggestions(['yoga','flow-yoga','power-yoga'],'Junior').length,1);});
check('Duplicate interests cannot inflate scores',()=>{assert.equal(m.suggestions(['strength','strength'],'First year')[0].score,m.suggestions(['strength'],'First year')[0].score);});
check('No unrelated students without explicit sample-contact opt-in',()=>{assert.equal(m.suggestions(['archery'],'First year').length,0);assert(m.suggestions(['archery'],'First year',true).every(p=>p.contact));});
check('First-year groups are cohort-specific',()=>{assert(m.groupSuggestions(['strength'],'First year').some(g=>g.name==='New students - Weightlifting'));assert(!m.groupSuggestions(['strength'],'Junior').some(g=>g.cohort==='First year'));assert.equal(m.groupSuggestions(['nonexistent'],'First year').length,0);});
const joined={...m.emptySocial,connections:['maya'],groups:m.groupSuggestions(['strength'],'First year')};
check('Only joined groups and connected friends accept messages',()=>{assert.notEqual(m.appendMessage(joined,'dm:maya','hi'),joined);assert.notEqual(m.appendMessage(joined,'first:strength','hi'),joined);assert.equal(m.appendMessage(joined,'dm:noor','hi'),joined);assert.equal(m.appendMessage(joined,'all:yoga','hi'),joined);});
check('Blank and overlength messages cannot be added',()=>{assert.equal(m.appendMessage(joined,'dm:maya','  '),joined);assert.equal(m.appendMessage(joined,'dm:maya','a'.repeat(501)),joined);});
check('Message updates are immutable and reload-valid',()=>{const next=m.appendMessage(joined,'dm:maya',' Hello ');assert.equal(next.messages['dm:maya'][0].text,'Hello');assert.equal(joined.messages['dm:maya'],undefined);assert(m.isSocial(JSON.parse(JSON.stringify(next))));});
check('Malformed saved state is rejected including forged groups',()=>{for(const bad of [null,{}, {...joined,groups:[null]}, {...joined,groups:[{id:'first:strength',name:'wrong',interest:'strength',cohort:'All years'}]}, {...joined,messages:{'dm:maya':[null]}},{...joined,messages:[]},{...joined,messages:{'dm:maya':[{id:'1',text:'x',time:'not-a-date'}]}}])assert.equal(m.isSocial(bad),false);});
check('Workout summaries exclude private notes and handle cardio',()=>{const summary=m.workoutSummary({id:1,exercise:'Bench press',sets:3,volume:3520,notes:'PRIVATE'});assert(!summary.includes('PRIVATE'));assert(summary.includes('3 sets'));assert.equal(m.workoutSummary({id:1,exercise:'30 min cardio',sets:0,volume:0,notes:'PRIVATE'}),'30 min cardio');});
console.log(count+' social checks passed; '+catalog.INTERESTS.length+' selectable interests.');
