import React, { useRef, useState } from 'react';
import { FlatList, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Ionicons from '@expo/vector-icons/Ionicons';
import Conversation, { ModalFrame } from './Conversation';
import { RecBrand, RecEmblem, RecSymbol } from './RecVisual';
import { useProfile } from './onboarding/ProfileContext';
import { initials } from './onboarding/model';
import { useSocial } from './social';
import { PEOPLE, Workout } from './socialModel';
import { useWorkoutFeed } from './workoutFeed';
import { addComment, authorName, commentsFor, FeedWorkout, friendUpdates, makePrivate, publicWorkout, removeComment, toggleLike, visibleWorkouts } from './workoutFeedModel';
import { C, s } from './styles';

type Destination = 'Activity' | 'Classes' | 'Community' | 'Profile';
type IconName = React.ComponentProps<typeof Ionicons>['name'];
const activityNames = { strength: 'Strength', track: 'Movement', studio: 'Mind & body', aquatics: 'Swimming' };
function Glyph({ name, color = C.ink, size = 21 }: { name: IconName; color?: string; size?: number }) { return <Ionicons name={name} color={color} size={size}/>; }
function Face({ id, small = false }: { id: string; small?: boolean }) {
  const { profile } = useProfile();
  return <View style={[f.face, small && { width: 34, height: 34 }, id === 'you' && { backgroundColor: C.navy }]}><Text style={[f.initials, id === 'you' && { color: 'white' }]}>{id === 'you' ? initials(profile) : authorName(id).split(' ').map(x => x[0]).join('')}</Text></View>;
}
function Action({ label, icon, onPress, active, disabled, a11y }: { label: string; icon: IconName; onPress: () => void; active?: boolean; disabled?: boolean; a11y?: string }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={a11y || label} accessibilityState={{ disabled, ...(active === undefined ? {} : { selected: active }) }} aria-pressed={active} disabled={disabled} onPress={onPress} style={({ pressed }) => [f.cardAction, pressed && f.pressed, disabled && { opacity: .4 }]}><Glyph name={icon} size={19} color={active ? C.blue : C.muted}/><Text style={[f.actionText, active && { color: C.blue }]}>{label}</Text></Pressable>;
}
function WorkoutContext({ workout }: { workout: FeedWorkout }) {
  return <View style={f.context}><RecEmblem kind={workout.kind} size={26} color={C.blue}/><View style={{ flex: 1 }}><Text style={f.name}>{workout.title}</Text><Text style={f.meta}>{authorName(workout.authorId)} · Public workout</Text></View></View>;
}

export default function HomeFeed({ workouts, navigate, notify }: { workouts: Workout[]; navigate: (route: Destination) => void; notify: (text: string) => void }) {
  const social = useSocial(); const feed = useWorkoutFeed();
  const [scope, setScope] = useState<'Friends' | 'Campus'>(social.data.connections.length ? 'Friends' : 'Campus');
  const [panel, setPanel] = useState<'notifications' | 'messages' | null>(null);
  const [discussion, setDiscussion] = useState<string | null>(null);
  const [connectTo, setConnectTo] = useState<FeedWorkout | null>(null);
  const [chat, setChat] = useState<{ thread: string; draft?: string; context?: string } | null>(null);
  const updates = friendUpdates(feed.data, social.data.connections);
  const unread = updates.filter(w => !feed.data.read.includes(w.id)).length;
  const found = visibleWorkouts(feed.data, social.data.connections, scope);
  const selected = discussion ? publicWorkout(feed.data, discussion) : undefined;
  function message(workout: FeedWorkout) {
    if (!social.data.connections.includes(workout.authorId)) { setConnectTo(workout); return; }
    openEncouragement(workout);
  }
  function openEncouragement(workout: FeedWorkout) {
    setChat({ thread: `dm:${workout.authorId}`, draft: `Nice work on “${workout.title}”!`, context: workout.title });
  }
  const actions: { title: string; label: string; symbol: RecSymbol; route: Destination }[] = [
    { title: 'Log a\nworkout', label: 'Log a workout', symbol: 'strength', route: 'Activity' },
    { title: 'Find a\nclass', label: 'Find a class', symbol: 'studio', route: 'Classes' },
    { title: 'Meet your\npack', label: 'Meet your pack', symbol: 'community', route: 'Community' },
  ];
  const header = <>
    <View style={f.quickActions}>{actions.map((a, i) => <Pressable key={a.route} accessibilityRole="button" accessibilityLabel={a.label} onPress={() => navigate(a.route)} style={({ pressed }) => [f.quickAction, i === 0 && f.primaryQuick, pressed && { opacity: .75 }]}><RecEmblem kind={a.symbol} color={i === 0 ? 'white' : C.blue} size={29}/><Text style={[f.quickLabel, i === 0 && { color: 'white' }]}>{a.title}</Text><View style={f.quickArrow}><Glyph name="arrow-forward" size={12} color={i === 0 ? '#C9D9FF' : C.muted}/></View></Pressable>)}</View>
    <View style={f.feedHeading}><Text style={f.heading}>Workout feed</Text><Text style={f.meta}>Demo community</Text></View>
    <View style={f.filters} accessibilityRole="tablist">{(['Friends', 'Campus'] as const).map(t => <Pressable key={t} accessibilityRole="tab" accessibilityState={{ selected: scope === t }} aria-selected={scope === t} onPress={() => setScope(t)} style={[f.filter, scope === t && f.filterActive]}><Text style={[f.filterText, scope === t && { color: C.navy }]}>{t}</Text>{scope === t && <View style={f.filterDot}/>}</Pressable>)}<View style={{ flex: 1 }}/><Glyph name="globe-outline" size={13} color={C.muted}/><Text style={f.publicLabel}>Public only</Text></View>
    {scope === 'Campus' && !social.data.connections.length && <Text style={f.discoveryHint}>Find a familiar face. Connect to build your Friends feed.</Text>}
    {!!feed.error && <Text accessibilityRole="alert" style={f.error}>{feed.error}</Text>}
    {!!social.error && <Text accessibilityRole="alert" style={f.error}>{social.error}</Text>}
  </>;
  return <SafeAreaView edges={['top']} style={f.screen}>
    <View style={f.header}><RecBrand/><View style={f.headerActions}><Pressable accessibilityRole="button" accessibilityLabel={unread ? `Notifications, ${unread} unread` : 'Notifications'} onPress={() => setPanel('notifications')} style={f.headerButton}><Glyph name="notifications-outline" size={23}/>{unread > 0 && <View style={f.unreadDot}/>}</Pressable><Pressable accessibilityRole="button" accessibilityLabel="Messages" onPress={() => setPanel('messages')} style={f.headerButton}><Glyph name="chatbubbles-outline" size={23}/></Pressable></View></View>
    <FlatList data={found} keyExtractor={w => w.id} ListHeaderComponent={header} contentContainerStyle={f.feed} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled"
      ListEmptyComponent={<View style={f.empty}><RecEmblem kind="community" size={44} color={C.blue}/><Text style={f.emptyTitle}>Your crew’s next chapter.</Text><Text style={f.emptyCopy}>Public workouts from your connections will land here. Find your people, then cheer them on.</Text><Pressable accessibilityRole="button" onPress={() => setScope('Campus')} style={s.button}><Text style={s.buttonText}>Explore campus workouts</Text></Pressable></View>}
      ListFooterComponent={<Text style={f.footnote}>A little encouragement goes a long way.{'\n'}Sample people · Activity stays on this device.</Text>}
      renderItem={({ item: w }) => {
        const connected = social.data.connections.includes(w.authorId);
        const liked = feed.data.liked.includes(w.id); const commentCount = commentsFor(feed.data, w.id).length;
        return <View style={f.card}>
          <View style={f.author}><Face id={w.authorId}/><View style={{ flex: 1 }}><Text style={f.name}>{authorName(w.authorId)}</Text><Text style={f.meta}>{w.authorId === 'you' ? 'Shared' : 'Sample'} · {new Date(w.time).toLocaleDateString([], { month: 'short', day: 'numeric' })} · Public</Text></View>{w.authorId !== 'you' && !connected && <Pressable accessibilityRole="button" accessibilityLabel={`Connect with ${authorName(w.authorId)}`} disabled={!social.ready} onPress={() => { social.update(d => ({ ...d, connections: [...new Set([...d.connections, w.authorId])] })); notify(`Connected with ${authorName(w.authorId)} in this demo.`); }} style={f.connect}><Text style={f.connectText}>Connect</Text></Pressable>}{connected && <Glyph name="people-outline" color={C.blue} size={18}/>}</View>
          <View style={f.cardBody}><View style={f.category}><RecEmblem kind={w.kind} size={21} color={C.blue}/><Text style={f.categoryText}>{activityNames[w.kind]} · UConn Rec</Text></View><Text style={f.workoutTitle}>{w.title}</Text>{!!w.caption && <Text style={f.caption}>{w.caption}</Text>}</View>
          <View style={f.metrics}>{w.metrics.map((m, i) => <View key={m.label} style={[f.metric, i > 0 && f.metricDivider]}><Text style={f.metricValue}>{m.value}</Text><Text style={f.metricLabel}>{m.label}</Text></View>)}</View>
          <View style={f.counts}><Text style={f.meta}>{w.likes + Number(liked)} {w.likes + Number(liked) === 1 ? 'like' : 'likes'}</Text><Pressable accessibilityRole="button" accessibilityLabel={`View ${commentCount} ${commentCount === 1 ? 'comment' : 'comments'} on ${w.title}`} onPress={() => setDiscussion(w.id)} style={{ paddingVertical: 8 }}><Text style={f.meta}>{commentCount} {commentCount === 1 ? 'comment' : 'comments'}</Text></Pressable></View>
          <View style={f.cardActions}><Action label={liked ? 'Liked' : 'Like'} a11y={`${liked ? 'Unlike' : 'Like'} ${w.title}`} active={liked} icon={liked ? 'heart' : 'heart-outline'} disabled={!feed.ready} onPress={() => feed.update(d => toggleLike(d, w.id))}/><Action label="Comment" a11y={`Comment on ${w.title}`} icon="chatbubble-outline" onPress={() => setDiscussion(w.id)}/>{w.authorId === 'you' ? <Action label="Unshare" a11y={`Make ${w.title} private`} icon="lock-closed-outline" onPress={() => { feed.update(d => makePrivate(d, w.id)); notify('Removed from the public feed. Your saved workout is still private.'); }}/> : <Action label="Message" a11y={`Message ${authorName(w.authorId)} about ${w.title}`} icon="paper-plane-outline" onPress={() => message(w)}/>}</View>
        </View>;
      }}/>
    {!!selected && <Comments workout={selected} close={() => setDiscussion(null)}/>}
    {panel === 'notifications' && <ModalFrame title="Notifications" subtitle="Updates from your Rec connections" closeLabel="Close notifications" close={() => setPanel(null)}><View style={f.panelIntro}><Text style={[f.meta, { flex: 1 }]}>{unread ? `${unread} unread ${unread === 1 ? 'update' : 'updates'}` : 'You’re all caught up.'}</Text><Pressable accessibilityRole="button" disabled={!unread} onPress={() => feed.update(d => ({ ...d, read: [...new Set([...d.read, ...updates.map(w => w.id)])] }))} style={{ padding: 12, opacity: unread ? 1 : .4 }}><Text style={s.link}>Mark all read</Text></Pressable></View><FlatList data={updates} keyExtractor={w => w.id} contentContainerStyle={{ padding: 18, gap: 10 }} ListEmptyComponent={<View style={f.empty}><Glyph name="notifications-outline" color={C.blue} size={36}/><Text style={f.emptyTitle}>Room for good news.</Text><Text style={f.emptyCopy}>Connect with people to see their public workout updates here.</Text></View>} renderItem={({ item: w }) => <Pressable accessibilityRole="button" accessibilityLabel={`Open update: ${authorName(w.authorId)}, ${w.title}`} onPress={() => { feed.update(d => ({ ...d, read: [...new Set([...d.read, w.id])] })); setPanel(null); setDiscussion(w.id); }} style={[f.notice, !feed.data.read.includes(w.id) && { backgroundColor: C.pale }]}><Face id={w.authorId}/><View style={{ flex: 1, gap: 4 }}><Text style={f.name}>{authorName(w.authorId)} shared a workout</Text><Text style={f.caption}>{w.title}</Text><Text style={f.meta}>Sample update · {feed.data.read.includes(w.id) ? 'Read' : 'Unread'}</Text></View></Pressable>}/></ModalFrame>}
    {panel === 'messages' && <Inbox close={() => setPanel(null)} open={thread => { setPanel(null); setChat({ thread }); }} findFriends={() => { setPanel(null); navigate('Community'); }}/>} 
    {!!connectTo && <ModalFrame title="A little hello first" subtitle={`Connect with ${authorName(connectTo.authorId)}`} closeLabel="Close connect dialog" close={() => setConnectTo(null)}><ScrollView contentContainerStyle={{ padding: 22, gap: 20 }}><WorkoutContext workout={connectTo}/><Text style={s.body}>Messages are for your connections. Add {authorName(connectTo.authorId).split(' ')[0]} to your demo pack, then write a little encouragement.</Text><Text style={f.meta}>This adds a local sample connection. No message is sent until you press Send.</Text><Pressable accessibilityRole="button" disabled={!social.ready} style={s.button} onPress={() => { social.update(d => ({ ...d, connections: [...new Set([...d.connections, connectTo.authorId])] })); openEncouragement(connectTo); setConnectTo(null); }}><Text style={s.buttonText}>Connect & write a message</Text></Pressable></ScrollView></ModalFrame>}
    {!!chat && <Conversation key={`${chat.thread}-${chat.context || 'inbox'}`} thread={chat.thread} initialDraft={chat.draft} activityContext={chat.context} workouts={workouts} close={() => setChat(null)}/>}
  </SafeAreaView>;
}

function Comments({ workout, close }: { workout: FeedWorkout; close: () => void }) {
  const feed = useWorkoutFeed(); const [draft, setDraft] = useState(''); const [status, setStatus] = useState(''); const list = useRef<FlatList>(null);
  const comments = commentsFor(feed.data, workout.id);
  return <ModalFrame title="A little encouragement" subtitle={`${comments.length} ${comments.length === 1 ? 'comment' : 'comments'}`} closeLabel="Close comments" close={close}>
    <WorkoutContext workout={workout}/>
    <FlatList ref={list} data={comments} keyExtractor={c => c.id} contentContainerStyle={{ padding: 20, gap: 22, flexGrow: 1 }} keyboardShouldPersistTaps="handled" onContentSizeChange={() => list.current?.scrollToEnd({ animated: false })} ListEmptyComponent={<View style={f.empty}><Glyph name="chatbubbles-outline" size={38} color={C.blue}/><Text style={f.emptyTitle}>Be their first cheer.</Text><Text style={f.emptyCopy}>A “nice work” can make someone’s day.</Text></View>} renderItem={({ item: c }) => <View style={{ flexDirection: 'row', gap: 11 }}><Face id={c.authorId} small/><View style={{ flex: 1, gap: 5 }}><Text style={f.name}>{authorName(c.authorId)} <Text style={f.meta}>· {c.authorId === 'you' ? new Date(c.time).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }) : 'Sample'}</Text></Text><Text selectable style={f.comment}>{c.text}</Text>{c.authorId === 'you' && <Pressable accessibilityRole="button" accessibilityLabel={`Delete your comment: ${c.text}`} onPress={() => { feed.update(d => removeComment(d, c.id)); setStatus('Comment deleted.'); }} style={{ alignSelf: 'flex-start', minHeight: 32, justifyContent: 'center' }}><Text style={f.meta}>Delete</Text></Pressable>}</View></View>}/>
    {!!feed.error && <Text accessibilityRole="alert" style={f.error}>{feed.error}</Text>}
    <View style={f.commentComposer}><TextInput accessibilityLabel="Workout comment" value={draft} onChangeText={setDraft} maxLength={500} multiline placeholder="Cheer them on…" placeholderTextColor={C.muted} style={f.commentInput}/><Pressable accessibilityRole="button" accessibilityLabel="Post comment" disabled={!draft.trim() || !feed.ready} onPress={() => { feed.update(d => addComment(d, workout.id, draft)); setDraft(''); setStatus('Comment added to this local workout.'); }} style={[f.send, (!draft.trim() || !feed.ready) && { opacity: .35 }]}><Glyph name="arrow-up" color="white" size={24}/></Pressable></View><Text accessibilityLiveRegion="polite" style={f.composerStatus}>{draft.length ? `${draft.length}/500 · Public comment` : status || 'Comments stay on this device in the demo.'}</Text>
  </ModalFrame>;
}

function Inbox({ close, open, findFriends }: { close: () => void; open: (thread: string) => void; findFriends: () => void }) {
  const { data } = useSocial(); const [query, setQuery] = useState('');
  const threads = [...PEOPLE.filter(p => data.connections.includes(p.id)).map(p => ({ id: `dm:${p.id}`, name: p.name, personId: p.id })), ...data.groups.map(g => ({ id: g.id, name: g.name, personId: '' }))].sort((a, b) => Date.parse(data.messages[b.id]?.at(-1)?.time || '1970-01-01') - Date.parse(data.messages[a.id]?.at(-1)?.time || '1970-01-01'));
  const matching = threads.filter(t => t.name.toLowerCase().includes(query.trim().toLowerCase()));
  return <ModalFrame title="Messages" subtitle="A session starts with a hello." closeLabel="Close messages" close={close}>
    <View style={{ padding: 18, gap: 12 }}><TextInput accessibilityLabel="Search conversations" placeholder="Find a friend or crew…" placeholderTextColor={C.muted} value={query} onChangeText={setQuery} style={s.input}/><Text style={f.meta}>Local demo conversations · No live messaging</Text></View>
    <FlatList data={matching} keyExtractor={t => t.id} contentContainerStyle={{ paddingHorizontal: 18, gap: 8 }} ListEmptyComponent={<View style={f.empty}><Glyph name="chatbubbles-outline" size={36} color={C.blue}/><Text style={f.emptyTitle}>{query ? 'No conversations found.' : 'Meet your next training buddy.'}</Text><Text style={f.emptyCopy}>{query ? 'Try another name.' : 'Connect with a friend or join a crew to start a conversation.'}</Text></View>} renderItem={({ item: t }) => <Pressable accessibilityRole="button" accessibilityLabel={`Open conversation with ${t.name}`} onPress={() => open(t.id)} style={f.thread}>{t.personId ? <Face id={t.personId}/> : <View style={f.face}><RecEmblem kind="community" size={27} color={C.blue}/></View>}<View style={{ flex: 1, gap: 4 }}><Text style={f.name}>{t.name}</Text><Text numberOfLines={2} style={f.meta}>{data.messages[t.id]?.at(-1)?.text || 'Say hello. Plan something good.'}</Text></View><Glyph name="chevron-forward" size={16} color={C.muted}/></Pressable>}/>
    <View style={{ padding: 20 }}><Pressable accessibilityRole="button" onPress={findFriends} style={[s.button, s.secondary]}><Text style={[s.buttonText, { color: C.blue }]}>Find your pack</Text></Pressable></View>
  </ModalFrame>;
}

const f = StyleSheet.create({
  screen: { flex: 1, backgroundColor: C.bg }, header: { paddingHorizontal: 18, paddingTop: 10, paddingBottom: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: 'white', borderBottomWidth: 1, borderBottomColor: C.line }, headerActions: { flexDirection: 'row', gap: 2 }, headerButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 22 }, unreadDot: { position: 'absolute', right: 10, top: 8, width: 7, height: 7, borderRadius: 4, backgroundColor: C.blue, borderWidth: 1, borderColor: 'white' },
  feed: { paddingHorizontal: 16, paddingBottom: 14 }, quickActions: { flexDirection: 'row', gap: 9, paddingVertical: 18 }, quickAction: { flex: 1, backgroundColor: 'white', borderWidth: 1, borderColor: C.line, borderRadius: 17, padding: 14, gap: 10, minHeight: 108 }, primaryQuick: { backgroundColor: C.navy, borderColor: C.navy }, quickLabel: { fontSize: 12, lineHeight: 17, fontWeight: '600', color: C.navy }, quickArrow: { position: 'absolute', right: 11, top: 13 },
  feedHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 1, marginBottom: 4 }, heading: { fontSize: 21, fontWeight: '700', color: C.navy, letterSpacing: -.6 }, filters: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 13, borderBottomWidth: 1, borderColor: C.line }, filter: { minHeight: 46, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 6, borderBottomWidth: 2, borderBottomColor: 'transparent' }, filterActive: { borderBottomColor: C.blue }, filterText: { color: C.muted, fontSize: 13, fontWeight: '600' }, filterDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: C.blue }, publicLabel: { color: C.muted, fontSize: 10 }, discoveryHint: { color: C.muted, fontSize: 12, lineHeight: 18, marginBottom: 14 },
  card: { backgroundColor: 'white', borderWidth: 1, borderColor: C.line, borderRadius: 20, marginBottom: 14, overflow: 'hidden' }, author: { flexDirection: 'row', gap: 10, alignItems: 'center', paddingHorizontal: 15, paddingTop: 16 }, face: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#E4EAF4', alignItems: 'center', justifyContent: 'center' }, initials: { fontWeight: '700', color: C.navy, fontSize: 12 }, name: { fontSize: 13, lineHeight: 19, fontWeight: '700', color: C.navy }, meta: { fontSize: 11, lineHeight: 17, color: C.muted }, connect: { minHeight: 44, justifyContent: 'center', paddingLeft: 6 }, connectText: { color: C.blue, fontWeight: '600', fontSize: 11 }, cardBody: { paddingHorizontal: 16, paddingTop: 15, paddingBottom: 17, gap: 8 }, category: { flexDirection: 'row', alignItems: 'center', gap: 7 }, categoryText: { fontSize: 10, color: C.blue, fontWeight: '600', letterSpacing: .3 }, workoutTitle: { color: C.navy, fontSize: 21, lineHeight: 26, fontWeight: '700', letterSpacing: -.5 }, caption: { color: C.ink, fontSize: 13, lineHeight: 20 }, metrics: { flexDirection: 'row', marginHorizontal: 15, backgroundColor: C.navy, borderRadius: 13, paddingVertical: 17 }, metric: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 5, paddingHorizontal: 4 }, metricDivider: { borderLeftWidth: 1, borderColor: '#263654' }, metricValue: { color: 'white', fontSize: 22, lineHeight: 27, fontWeight: '600', letterSpacing: -.6, fontVariant: ['tabular-nums'] }, metricLabel: { color: '#C1CDE1', fontSize: 10, lineHeight: 14 }, counts: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, marginTop: 5 }, cardActions: { flexDirection: 'row', borderTopWidth: 1, borderColor: C.line }, cardAction: { flex: 1, minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 }, actionText: { fontSize: 11, fontWeight: '600', color: C.muted }, pressed: { backgroundColor: C.pale },
  empty: { alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12, paddingVertical: 30, gap: 14 }, emptyTitle: { fontSize: 22, fontWeight: '700', color: C.navy, textAlign: 'center', letterSpacing: -.5 }, emptyCopy: { color: C.muted, textAlign: 'center', fontSize: 14, lineHeight: 22 }, footnote: { color: C.muted, textAlign: 'center', fontSize: 11, lineHeight: 19, paddingTop: 8, paddingBottom: 14 }, error: { color: '#8B3B18', backgroundColor: '#FFF1D6', padding: 12, fontSize: 12, lineHeight: 18 },
  context: { margin: 18, marginBottom: 0, padding: 14, borderRadius: 14, backgroundColor: C.pale, flexDirection: 'row', alignItems: 'center', gap: 12 }, panelIntro: { paddingLeft: 20, paddingRight: 8, flexDirection: 'row', alignItems: 'center' }, notice: { padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 16, borderWidth: 1, borderColor: C.line }, thread: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 16, borderBottomWidth: 1, borderColor: C.line }, comment: { fontSize: 14, lineHeight: 22, color: C.ink }, commentComposer: { paddingHorizontal: 16, paddingTop: 12, flexDirection: 'row', alignItems: 'flex-end', gap: 10, borderTopWidth: 1, borderColor: C.line }, commentInput: { flex: 1, minHeight: 46, maxHeight: 100, backgroundColor: C.bg, borderRadius: 20, padding: 13, color: C.ink, fontSize: 14, lineHeight: 20 }, send: { height: 44, width: 44, borderRadius: 22, backgroundColor: C.blue, alignItems: 'center', justifyContent: 'center' }, composerStatus: { padding: 10, textAlign: 'center', fontSize: 10, color: C.muted },
});
